[tool.black]
line-length = 100
target-version = ['py39']
skip-string-normalization = true


[build-system]
requires = [
    "setuptools>=61",
    "setuptools-scm"
]
build-backend = "setuptools.build_meta"


[project]
name = "xarray-schema"
description = "Schema validation for Xarray objects"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Xarray-schema Developers", email = "joe@carbonplan.org"}]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
]
dynamic = ["version"]
dependencies = [
    "xarray>=0.16"
]
[project.optional-dependencies]

dev = [
"jsonschema",
"pytest",
"pytest-cov",
"mypy==0.982",
"types-jsonschema",
"types-setuptools==65.5.0.3"
]
[project.urls]
documentation = "https://xarray-schema.readthedocs.io/"
repository = "https://github.com/xarray-contrib/xarray-schema"

[tool.setuptools.packages.find]
include = ["xarray_schema*"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "dirty-tag"
fallback_version = "999"

[tool.isort]
profile = "black"
skip_gitignore = true


[tool.pytest.ini_options]
log_cli = true
log_level = "INFO"
